-- Add new columns for property details
ALTER TABLE properties 
ADD COLUMN IF NOT EXISTS room_count TEXT,
ADD COLUMN IF NOT EXISTS floor_number INTEGER,
ADD COLUMN IF NOT EXISTS building_age TEXT,
ADD COLUMN IF NOT EXISTS heating_type TEXT,
ADD COLUMN IF NOT EXISTS balcony BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS elevator BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS furnished BOOLEAN DEFAULT false,
-- Add new columns for property details
ALTER TABLE properties 
ADD COLUMN IF NOT EXISTS room_count TEXT,
ADD COLUMN IF NOT EXISTS floor_number INTEGER,
ADD COLUMN IF NOT EXISTS building_age TEXT,
ADD COLUMN IF NOT EXISTS heating_type TEXT,
ADD COLUMN IF NOT EXISTS balcony BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS elevator BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS furnished BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS parking_spots INTEGER,
ADD COLUMN IF NOT EXISTS crane BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS entrance_height_m NUMERIC,
ADD COLUMN IF NOT EXISTS ground_loading BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS zoning_status TEXT,
ADD COLUMN IF NOT EXISTS gabari NUMERIC,
ADD COLUMN IF NOT EXISTS kak NUMERIC,
ADD COLUMN IF NOT EXISTS administrative_building BOOLEAN DEFAULT false;
